name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and test backend
        run: |
          cd backend_express_mongodb
          docker build -t backend .
          docker run -d --name backend -p 3000:3000 backend
          docker exec backend npm test
        continue-on-error: true

      - name: Stop and remove backend container
        if: always()
        run: |
          docker stop backend || true
          docker rm backend || true

      - name: Build and test frontend
        run: |
          cd frontend_vuejs/citations-api
          docker build -t frontend .
          docker run -d --name frontend -p 5173:5173 frontend
          docker exec frontend npm run test:unit
        continue-on-error: true

      - name: Stop and remove frontend container
        if: always()
        run: |
          docker stop frontend || true
          docker rm frontend || true

      - name: Debug - List running containers
        run: docker ps -a

      - name: Debug - Show backend logs
        run: docker logs backend

      - name: Debug - Show frontend logs
        run: docker logs frontend

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend_vuejs/citations-api
          command: npm run test:e2e
          wait-on: "http://localhost:5173"
        env:
          CYPRESS_BASE_URL: http://localhost:5173

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            ./backend_express_mongodb/coverage
            ./frontend_vuejs/citations-api/coverage
